#!/usr/bin/env python3
"""
run_all.py
A wrapper script to execute Phase 1 (packet_factory.py) and Phase 2 (main.py)
sequentially on a single PCAP file.

Usage:
  python3 run_all.py path/to/capture.pcap
"""

import os
import sys
import subprocess
from pathlib import Path
import hashlib
import getpass
import socket
import datetime
import json

def hash_file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 run_all.py <pcap_file>")
        sys.exit(1)
        
    pcap_path = Path(sys.argv[1]).resolve()
    
    if not pcap_path.exists():
        print(f"Error: PCAP file not found at {pcap_path}")
        sys.exit(1)
        
    stem = pcap_path.stem

    print(f"============================================================")
    print(f" [Forensics] Calculating PCAP SHA-256 hash...")
    pcap_hash = hash_file_sha256(pcap_path)
    operator = getpass.getuser()
    hostname = socket.gethostname()
    start_time = datetime.datetime.now(datetime.timezone.utc).isoformat()
    print(f"   Hash: {pcap_hash}")
    print(f"   Operator: {operator}@{hostname}")

    print(f"============================================================")
    print(f" PHASE 1: Extracting and building Data Lake for {stem}")
    print(f"============================================================")
    
    base_processed = os.environ.get("PROCESSED_DIR", "processed")
    try:
        subprocess.run([sys.executable, "packet_factory.py", str(pcap_path), "--processed-dir", base_processed], check=True)
    except subprocess.CalledProcessError:
        print("\n❌ Phase 1 failed! Aborting.")
        sys.exit(1)
        
    print(f"\n============================================================")
    print(f" PHASE 2: Enriching and processing IOCs for {stem}")
    print(f"============================================================")
    
    # We pass the expected processed directory to main.py so it explicitly
    # targets the output generated by Phase 1, avoiding any auto-detect confusion.
    base_processed = os.environ.get("PROCESSED_DIR", "processed")
    processed_target = os.path.join(base_processed, stem)
    
    env = os.environ.copy()
    env["FORENSIC_PCAP_HASH"] = pcap_hash
    env["FORENSIC_OPERATOR"] = operator
    env["FORENSIC_HOSTNAME"] = hostname
    env["FORENSIC_START_TIME"] = start_time
    
    try:
        subprocess.run([sys.executable, "ioc_extractor.py", processed_target], check=True, env=env)
    except subprocess.CalledProcessError:
        print("\n❌ Phase 2 failed!")
        sys.exit(1)
        
    print(f"\n============================================================")
    print(f" PHASE 3: Correlation & Attack Chain Scoring for {stem}")
    print(f"============================================================")
    
    # Phase 2 creates an output folder like 'phase2_output/Hive_20260428_120000/'
    # We need to find the most recent one for this stem.
    phase2_base = Path(os.environ.get("OUTPUT_DIR", "phase2_output"))
    matching_dirs = sorted(
        [d for d in phase2_base.iterdir() if d.is_dir() and d.name.startswith(stem + "_")],
        key=os.path.getmtime,
        reverse=True
    )
    
    if matching_dirs:
        latest_phase2 = matching_dirs[0]
        try:
            subprocess.run([sys.executable, "correlation.py", processed_target, str(latest_phase2)], check=True)
        except subprocess.CalledProcessError:
            print("\n❌ Phase 3 failed!")
            sys.exit(1)
    else:
        print(f"⚠️ Could not locate Phase 2 output directory for {stem} to run Phase 3.")
        
    if matching_dirs:
        latest_phase2 = matching_dirs[0]
        print(f"\n============================================================")
        print(f" FORENSICS: Generating Integrity Manifest")
        print(f"============================================================")
        manifest = {
            "pcap_file": pcap_path.name,
            "pcap_sha256": pcap_hash,
            "operator": operator,
            "hostname": hostname,
            "timestamp_utc": start_time,
            "file_hashes": {}
        }
        
        # Hash all output files
        for f in latest_phase2.iterdir():
            if f.is_file() and f.name != "manifest.json":
                manifest["file_hashes"][f.name] = hash_file_sha256(f)
                
        # Hash all extracted payloads
        extracted_dir = Path(processed_target) / "extracted_payloads"
        if extracted_dir.exists() and extracted_dir.is_dir():
            for f in extracted_dir.iterdir():
                if f.is_file():
                    manifest["file_hashes"][f"extracted_payloads/{f.name}"] = hash_file_sha256(f)
                    
        manifest_path = latest_phase2 / "manifest.json"
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest, f, indent=2)
            
        print(f"✅ Cryptographic manifest generated: {manifest_path}")
        
    print("\n✅ Complete Pipeline Finished Successfully!")

if __name__ == "__main__":
    main()
